management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
spring:
  application:
    name: sys-kilo-doc-aggregator
  data:
    cassandra:
      local-datacenter: datacenter1
      port: 9042
      contact-points: localhost
      keyspace-name: examplesys
logging:
  file:
    path: .
    name: spring-boot.log
  level:
    org:
      springframework:
        web: DEBUG
server:
  port: ${PORT:8080}
  kafka:
    consumer:
      auto-offset-reset: latest
      bootstrap-servers: localhost:9092
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
topic:
  name:
    consumer: doc

